name: Demo3 
on:
  push:
    branches:
      - demo3

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - env:
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          gh issue edit $ISSUE_URL --add-label "triage"
