name: Github Actions Demo
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: |
          chmod +x .github/workflows/setup_server.sh
          .github/workflows/setup_server.sh
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: |
          chmod +x .github/workflows/build_server.sh
          .github/workflows/build_server.sh
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: |
          chmod +x .github/workflows/test_server.sh
          .github/workflows/test_server.sh
  deploy_staging:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: |
          echo "deploying to staging"
  deploy_prod:
    runs-on: ubuntu-latest
    needs: deploy_staging
    steps:
      - run: |
          echo "deploying to prod"
