name: Github Actions Demo
on:
  push:
    branches:
      - main
jobs:
  explore-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Retrive secrets
        env:
          super_secret: ${{ secrets.SUPER_SECRET }}
        run: |
          echo "super secret is $super_secret"

  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code 
        uses: actions/checkout@v4
      - run: |
          chmod +x ./setup_server.sh
          ./setup_server.sh
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out repo code 
        uses: actions/checkout@v4
      - run: |
          chmod +x ./build_server.sh
          ./build_server.sh
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repo code 
        uses: actions/checkout@v4
      - run: |
          chmod +x ./test_server.sh
          ./test_server.sh
  deploy_staging:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: |
          echo "deploying to staging"
  deploy_prod:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: |
          echo "deploying to prod"
