name: GitHub Actions Demo 
run-name: ${{ github.actor }} is testing out Github actions 
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "event name ${{ github.event_name }}"
          echo "Job run on os ${{ runner.os }}"
          echo "Name of branch is ${{ github.ref }} name repo is ${{ github.repository }}"
      - name: Check out repo code 
        uses: actions/checkout@v4
      - run: |
          echo "The ${{ github.repository }} repo has been cloned to the runner"
          echo "The workflow is now ready to test your code on the runner"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: |
            echo "This job's status is ${{ job.status }}"       
